spring:
  application:
    name: Cognify

  datasource:
    url: jdbc:postgresql://localhost:9000/cognify-DB
    username: postgres
    password: 2611
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
