spring:
  application:
    name: Cognify

  datasource:
    url: jdbc:postgresql://localhost:9000/cognify-DB
    username: postgres
    password: 2611
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#  ai:
#    openai:
#      api-key:
#      base-url: https://openrouter.ai/api
#      chat:
#        options:
#          #          model: x-ai/grok-code-fast-1
##          model: google/gemini-3-flash-preview
#          model: qwen/qwen3-next-80b-a3b-instruct:free
#          temperature: 0.0

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl

stripe:
  api:
#    secret: sk_test_51TI2NmG0w0p89QloHTGGR2fVC1nqRWJpCX1hFESwF2mronpuIqYLezp9W8nz0iVs2tvTitqYrb9eLCCxmzBSDXkM00an0XxeSG
    secret: sk_test_51TI2NmG0w0p89QloHTGGR2fVC1nqRWJpCX1hFESwF2mronpuIqYLezp9W8nz0iVs2tvTitqYrb9eLCCxmzBSDXkM00an0XxeSG
  webhook:
    secret: whsec_aa738954b823de3ac5820441aeea1d172b536aeb2ac7ee9251b4eba942933301

client.url: http://localhost:8080
